# Generated by Django 5.2.3 on 2025-06-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('nome', 'categoria')},
        ),
    ]
